// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1PQBU0AEF8vfF_1U5G1zknEgUpFRgNeo',
    appId: '1:648934170892:web:875945f7085ff12f422929',
    messagingSenderId: '648934170892',
    projectId: 'education-on-move-nandini',
    authDomain: 'education-on-move-nandini.firebaseapp.com',
    databaseURL: 'https://education-on-move-nandini-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'education-on-move-nandini.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuqphz2_Q6wC_38LjknUernBOnra3YbXU',
    appId: '1:648934170892:ios:3ee495dbc6fc0c93422929',
    messagingSenderId: '648934170892',
    projectId: 'education-on-move-nandini',
    databaseURL: 'https://education-on-move-nandini-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'education-on-move-nandini.appspot.com',
    iosBundleId: 'com.example.eLearning1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuqphz2_Q6wC_38LjknUernBOnra3YbXU',
    appId: '1:648934170892:ios:3ee495dbc6fc0c93422929',
    messagingSenderId: '648934170892',
    projectId: 'education-on-move-nandini',
    databaseURL: 'https://education-on-move-nandini-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'education-on-move-nandini.appspot.com',
    iosBundleId: 'com.example.eLearning1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1PQBU0AEF8vfF_1U5G1zknEgUpFRgNeo',
    appId: '1:648934170892:web:900b3cb7a990a103422929',
    messagingSenderId: '648934170892',
    projectId: 'education-on-move-nandini',
    authDomain: 'education-on-move-nandini.firebaseapp.com',
    databaseURL: 'https://education-on-move-nandini-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'education-on-move-nandini.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAButmOgfQI2A0Fw9bEaiRUZQi-S1q3LMA',
    appId: '1:648934170892:android:edfcbd8bb01bc5dd422929',
    messagingSenderId: '648934170892',
    projectId: 'education-on-move-nandini',
    databaseURL: 'https://education-on-move-nandini-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'education-on-move-nandini.appspot.com',
  );

}